
name: Executable Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    
      # Check-out repository
      - uses: actions/checkout@v3
      
      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'

      - run: |
          python -m pip install --upgrade pipenv
          pipenv update -d

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: FluentPython
          onefile: true
          enable-plugins: pyside6
          disable-console: true
          
      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            